//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JewelryStore.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Populated.
        /// </summary>
        internal static string DataPopulated {
            get {
                return ResourceManager.GetString("DataPopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount % : .
        /// </summary>
        internal static string DiscountInPercentage {
            get {
                return ResourceManager.GetString("DiscountInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Gold Price (per gram) : .
        /// </summary>
        internal static string EnterGoldPricePerGram {
            get {
                return ResourceManager.GetString("EnterGoldPricePerGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username:.
        /// </summary>
        internal static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Weight (in grams) : .
        /// </summary>
        internal static string EnterWeightInGrams {
            get {
                return ResourceManager.GetString("EnterWeightInGrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file found!.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Price (per gram) : .
        /// </summary>
        internal static string GoldPricePerGram {
            get {
                return ResourceManager.GetString("GoldPricePerGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Price should be greater than zero.
        /// </summary>
        internal static string GoldPricePerGramGreaterThanZero {
            get {
                return ResourceManager.GetString("GoldPricePerGramGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path detected!.
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your Username or Password.
        /// </summary>
        internal static string LogInError {
            get {
                return ResourceManager.GetString("LogInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged In Successfully.
        /// </summary>
        internal static string LogInSuccessful {
            get {
                return ResourceManager.GetString("LogInSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter any of the below options:
        ///1. To Print to Screen Press S
        ///2. To Print to File  Press F
        ///3. To Print to Paper Press P
        ///4. To Close Press X.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a registered User.
        /// </summary>
        internal static string Not_A_RegisteredUser {
            get {
                return ResourceManager.GetString("Not_A_RegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading in app settings.
        /// </summary>
        internal static string ReadErrorInAppsettings {
            get {
                return ResourceManager.GetString("ReadErrorInAppsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price (after discount) : .
        /// </summary>
        internal static string TotalPriceAfterDiscount {
            get {
                return ResourceManager.GetString("TotalPriceAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price : .
        /// </summary>
        internal static string TotalPriceBeforeDiscount {
            get {
                return ResourceManager.GetString("TotalPriceBeforeDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required.
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (in grams) : .
        /// </summary>
        internal static string WeightInGrams {
            get {
                return ResourceManager.GetString("WeightInGrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (in grams) should be greater than zero.
        /// </summary>
        internal static string WeightInGramsGreaterThanZero {
            get {
                return ResourceManager.GetString("WeightInGramsGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome: .
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
